# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 00:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereco')),
                ('cnpj', models.CharField(max_length=255, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('mes_ano', models.DateTimeField(verbose_name='Mes ano')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoHabitacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao')),
                ('qtd_unidades', models.IntegerField(verbose_name='Qtd unidades')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_habitacionais', to='api.Condominio')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTaxa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('despesa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Despesa')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxaCondominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.DateTimeField(max_length=255, verbose_name='Mes ano')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data pagamento')),
                ('valor_pago', models.FloatField(blank=True, null=True, verbose_name='Valor pago')),
                ('valor_a_pagar', models.FloatField(blank=True, null=True, verbose_name='Valor a pagar')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('valor_rateado', models.BooleanField(verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeHabitacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao')),
                ('qtd_quartos', models.IntegerField(verbose_name='Qtd quartos')),
                ('ocupacao', models.CharField(choices=[('Proprietario', 'proprietario'), ('Inquilino', 'inquilino'), ('Vazio', 'vazio')], default='vazio', max_length=255, verbose_name='Ocupacao')),
                ('grupo_habitacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_habitacionais', to='api.GrupoHabitacional')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_unidades', to='api.Proprietario')),
            ],
        ),
        migrations.AddField(
            model_name='taxacondominio',
            name='unidade_habitacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_taxas', to='api.UnidadeHabitacional'),
        ),
        migrations.AddField(
            model_name='itemtaxa',
            name='taxa_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.TaxaCondominio'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='tipo_despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='api.TipoDespesa'),
        ),
    ]
