# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='mes_ano',
            field=models.DateField(verbose_name='Mes ano'),
        ),
        migrations.AlterField(
            model_name='taxacondominio',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data pagamento'),
        ),
        migrations.AlterField(
            model_name='taxacondominio',
            name='mes_ano',
            field=models.DateField(max_length=255, verbose_name='Mes ano'),
        ),
    ]
