# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180530_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtaxa',
            name='despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_da_despesa', to='api.Despesa'),
        ),
    ]
