# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180530_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxacondominio',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
