# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_taxacondominio_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxacondominio',
            old_name='data_pagamento',
            new_name='data_vencimento',
        ),
    ]
