# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180531_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='sindico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Proprietario'),
        ),
    ]
