# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_condominio_sindico'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='sindico',
            field=models.BooleanField(default=False, verbose_name='sindico'),
        ),
    ]
